### ISSUE TITLE
CentOS 8 is about to die, so we need to consider an alternative.

### ISSUE THREAD

**Issue by fu-sen** [domcloud/domcloud-io#16]
Both DOM Cloud 2 servers seem to use CentOS 8. However, this distro has been modified to be discontinued in 2021.
https://centos.org/distro-faq/
https://arstechnica.com/gadgets/2020/12/centos-shifts-from-red-hat-unbranded-to-red-hat-beta/

You should consider an alternative distribution for this and a plan to change the distribution of your server.

**Comment by willnode** [comment]
Wow. I wasn't aware of that.

From a quick read, it seems easy to switch over to the Stream version. But digging through articles makes me more cautious about it.

I will take more reading before taking any action about it.

**Comment by fu-sen** [comment]
Oh, I was right to create this issue. There should be some work on these in the next few months,
so be careful and informed and take action.

**Comment by fu-sen** [comment]
AWS and GCP (GCE) have added Rocky support. Probably a strong candidate for now:
https://aws.amazon.com/marketplace/pp/prodview-e4hjgjwq4baw2
https://cloud.google.com/compute/docs/images/os-details#vm-manager

However, there are activities in other contributions as well.

**Comment by willnode** [comment]
Good find. I just know Rocky Linux as well. It seems promising.

While I can deploy another VM overnight, I'd have to double think about replacing the existing one. Deploying a new server is not an option right now due to budget constraints, so I have to hot-swap the existing VM disk using image recovery. That would be a long downtime if I'm not prepared enough.

I'll put this as a backlog, there are some features in the portal I need to bring on first. The nyc-server is probably the first one to get replaced later this month.

**Comment by fu-sen** [comment]
The means of changing from CentOS to Rocky is still in its infancy. This also changes the kernel. In the worst case, it will not boot
Also, the means of consideration will obviously cause downtime and will need to be considered more carefully.

Can you launch an alternative VM for some money?

**Comment by willnode** [comment]
Well, do you want to test it? I have no problem spinning another one actually as long as it's getting used. I can just mark it beta or something.

**Comment by willnode** [comment]
I just sent you a reply email.

**Comment by fu-sen** [comment]
(We are working out of sight of you) ☕💻
